In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot('too good',40)

[36, 19]

In [5]:
vocab_size = 30
hot_reviews = [one_hot(x,vocab_size) for x in reviews]
hot_reviews

[[18, 8],
 [15, 1],
 [3, 2],
 [4, 15, 5],
 [5, 11, 20],
 [14, 8],
 [18, 11, 27],
 [5, 23],
 [5, 26],
 [17, 19]]

In [6]:
max_length = 3
padded_reviews = pad_sequences(hot_reviews,maxlen=max_length,padding="post")
padded_reviews

array([[18,  8,  0],
       [15,  1,  0],
       [ 3,  2,  0],
       [ 4, 15,  5],
       [ 5, 11, 20],
       [14,  8,  0],
       [18, 11, 27],
       [ 5, 23,  0],
       [ 5, 26,  0],
       [17, 19,  0]], dtype=int32)

In [19]:
embedded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation="sigmoid"))

In [20]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
X= padded_reviews
y= sentiment

In [22]:
model.fit(X,y,epochs=50,verbose=0)

In [23]:
loss,accuracy = model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - accuracy: 0.8000 - loss: 0.6383


In [24]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 3, 4)                │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 12)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              13 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 401 (1.57 KB)

 Trainable params: 133 (532.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 268 (1.05 KB)

In [27]:
# Purpuse is to retrieve the embedding vector
weights = model.get_layer("embedding").get_weights()[0]
len(weights)

30

In [30]:
# Nice -18. Amazing-15. Let's Check if they are similar.
weights[18], weights[15]

(array([ 0.02168505,  0.00729199, -0.02345584,  0.0313733 ], dtype=float32),
 array([-0.064684  , -0.0016401 ,  0.10888379, -0.03048784], dtype=float32))